from models import App
from scrapers import (
    scrape_sparkle,
    scrape_onepassword,
    scrape_adobeacrobatreader,
    scrape_androidstudio,
    scrape_atext,
    scrape_avidlink,
    scrape_awscli,
    scrape_blender,
    scrape_bbedit,
    scrape_github,
    scrape_microsoft_plist,
    scrape_logitune,
    scrape_affinity,
    scrape_mysqlworkbench,
    scrape_charlesproxy,
    scrape_isadora,
    scrape_labchart,
    scrape_googleearthpro,
    scrape_gpgtools,
    scrape_python,
    scrape_r,
    scrape_openai,
    scrape_gimp,
    scrape_codex,
    scrape_imazingprofileeditor,
    scrape_itsycal,
    scrape_nitropdfpro,
    scrape_oraclejava8,
    scrape_catalystbrowse,
    scrape_alfred,
    scrape_claude,
    scrape_druvainsync,
    scrape_elgatostreamdeck,
    scrape_figma,
    scrape_gemini,
    scrape_googlechrome,
    scrape_evernote,
    scrape_oktaverify,
    scrape_postman,
    scrape_pycharm,
    scrape_raspberrypiimager,
    scrape_openvpnconnect,
    scrape_opera,
    scrape_githubdesktop,
    scrape_sassafraskeyaccessmac,
    scrape_mafft,
    scrape_logioptionsplus,
    scrape_makemkv,
    scrape_displaylinkmanager,
    scrape_mestrenova,
    scrape_mp4joiner,
    scrape_parallels,
    scrape_sfsymbols,
    scrape_endnote,
    scrape_pymol,
    scrape_signal,
    scrape_slack,
    scrape_snagit,
    scrape_suspiciouspackage,
    scrape_coconutbattery,
    scrape_cycliqplus,
    scrape_dropbox,
    scrape_intellijidea,
    scrape_fetch,
    scrape_filemakerpro,
    scrape_microsoft_edge,
    scrape_freemind,
    scrape_plex,
    scrape_pgadmin4,
    scrape_sublime,
    scrape_pacifist,
    scrape_teamviewerqs,
    scrape_telegram,
    scrape_theunarchiver,
    scrape_mozilla,
    scrape_touchdesigner,
    scrape_visualstudiocode,
    scrape_vlc,
    scrape_nvivo,
    scrape_voodoopad,
    scrape_webex,
    scrape_wireshark,
    scrape_whatsapp,
    scrape_yubicoauth,
    scrape_zotero,
    scrape_zoom
)

apps = [
    App(name="1Password", app_url="https://releases.1password.com/mac/", download_url="https://downloads.1password.com/mac/1Password.pkg", scraper=scrape_onepassword),
    App(name="Adobe Acrobat Reader", app_url="https://armmf.adobe.com/arm-manifests/mac/AcrobatDC/reader/current_version.txt", download_url_template="https://ardownload3.adobe.com/pub/adobe/acrobat/mac/AcrobatDC/{version}/AdobeReader{version}.dmg", scraper=scrape_adobeacrobatreader),
    App(name="Affinity Designer", app_url="https://store.serif.com/en-gb/update/macos/designer/2/", scraper=scrape_affinity),
    App(name="Affinity Photo", app_url="https://store.serif.com/en-gb/update/macos/photo/2/", scraper=scrape_affinity),
    App(name="Affinity Publisher", app_url="https://store.serif.com/en-gb/update/macos/publisher/2/", scraper=scrape_affinity),
    App(name="Alfred", app_url="https://www.alfredapp.com/app/update5/general.xml", scraper=scrape_alfred),
    App(name="Altair GraphQL", app_url="https://github.com/altair-graphql/altair", file_search_strings=["arm64", ".dmg"], scraper=scrape_github),
    App(name="Android Studio", app_url="https://developer.android.com/studio", scraper=scrape_androidstudio),
    App(name="API Utility", app_url="https://github.com/Jamf-Concepts/apiutil", file_search_strings=["zip"], scraper=scrape_github),
    App(name="Arc", app_url="https://releases.arc.net/updates.xml", sparkle_version_key="shortVersionString", scraper=scrape_sparkle),
    App(name="Artemis", app_url="https://github.com/sanger-pathogens/Artemis", file_search_strings=["dmg.gz"], scraper=scrape_github),
    App(name="aText", app_url="https://www.trankynam.com/atext", scraper=scrape_atext),
    App(name="Atom", app_url="https://github.com/atom/atom", file_search_strings=["mac.zip"], scraper=scrape_github),
    App(name="Audacity", app_url="https://github.com/audacity/audacity", file_search_strings=["universal.dmg"], scraper=scrape_github),
    App(name="Avid Link", app_url="https://www.avid.com/products/avid-link#Downloads", scraper=scrape_avidlink),
    App(name="AWS CLI", app_url="https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst", download_url="https://awscli.amazonaws.com/AWSCLIV2.pkg", scraper=scrape_awscli),
    App(name="Azure CLI", app_url="https://github.com/Azure/azure-cli", file_search_strings=["macos-arm64.tar.gz"], scraper=scrape_github),
    App(name="Balena Etcher", app_url="https://github.com/balena-io/etcher", file_search_strings=["arm64.dmg"], scraper=scrape_github),
    App(name="BBEdit", app_url="https://www.barebones.com/products/bbedit", scraper=scrape_bbedit),
    App(name="Blender", app_url="https://www.blender.org/download/", scraper=scrape_blender),
    App(name="Brave Browser", app_url="https://updates.bravesoftware.com/sparkle/Brave-Browser/stable/appcast.xml", sparkle_version_key="version", scraper=scrape_sparkle),
    App(name="Catalyst Browse", app_url="https://cs.d-imaging.sony.co.jp/coay5hz6MI/2Aext1Frsi?product=CatalystBrowse&lang=en", download_url="https://di.update.sony.net/NEX/ch4055c566/Catalyst_Browse.dmg", scraper=scrape_catalystbrowse),
    App(name="Charles Proxy", app_url="https://www.charlesproxy.com/download/latest-release", download_url_template="https://www.charlesproxy.com/assets/release/{version}/charles-proxy-{version}.dmg", scraper=scrape_charlesproxy),
    App(name="ChatGPT Atlas", app_url="https://persistent.oaistatic.com/atlas/public/sparkle_public_appcast.xml", scraper=scrape_openai),
    App(name="ChatGPT aka Codex", app_url="https://persistent.oaistatic.com/codex-app-prod/appcast.xml", scraper=scrape_openai),
    App(name="Claude", app_url="https://downloads.claude.ai/releases/darwin/universal/RELEASES.json", scraper=scrape_claude),
    App(name="coconutBattery", app_url="https://www.coconut-flavour.com/coconutbattery", scraper=scrape_coconutbattery),
    App(name="CodeRunner", app_url="https://coderunnerapp.com/appcast.xml", sparkle_version_key="shortVersionString", scraper=scrape_sparkle),
    App(name="Codex", app_url="https://persistent.oaistatic.com/codex-app-prod/appcast.xml", scraper=scrape_codex),
    App(name="Cyberduck", app_url="https://version.cyberduck.io/changelog.rss", sparkle_version_key="shortVersionString", scraper=scrape_sparkle),
    App(name="CycliqPlus", download_url="https://legacy.cycliq.com/software/cycliqplus/macos-silicon/", scraper=scrape_cycliqplus),
    App(name="DisplayLink Manager", app_url="https://www.synaptics.com", scraper=scrape_displaylinkmanager),
    App(name="dockutil", app_url="https://github.com/kcrawford/dockutil", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Draw IO", app_url="https://github.com/jgraph/drawio-desktop", file_search_strings=[".dmg", "arm64"], scraper=scrape_github),
    App(name="Dropbox", download_url="https://www.dropbox.com/download?plat=mac&full=1&arch=arm64", scraper=scrape_dropbox),
    App(name="Dupeguru", app_url="https://github.com/arsenetar/dupeguru", file_search_strings=["macOS"], scraper=scrape_github),
    App(name="Druva InSync", app_url="https://downloads.druva.com/insync/js/data.json", scraper=scrape_druvainsync),
    App(name="Elgato Stream Deck", app_url="https://gc-updates.elgato.com", scraper=scrape_elgatostreamdeck),
    App(name="EndNote", app_url="https://endnote.com/downloads/available-updates/", download_url_template="https://download.endnote.com/downloads/{version_maj}/EndNote{version_maj}Installer.dmg", scraper=scrape_endnote),
    App(name="Evernote", app_url="https://public.evernote.com/ddl-updater/updater/mac/public/latest-mac.yml", scraper=scrape_evernote),
    App(name="Fetch", app_url="https://fetchsoftworks.com", scraper=scrape_fetch),
    App(name="Figma", app_url="https://desktop.figma.com/mac-arm/RELEASE.json", scraper=scrape_figma),
    App(name="FileMaker Pro", app_url="https://www.filemaker.com/redirects/ss.txt", scraper=scrape_filemakerpro),
    App(name="Firefox", app_url="https://product-details.mozilla.org/1.0/firefox_versions.json", download_url_template="https://download-installer.cdn.mozilla.net/pub/firefox/releases/{version}/mac/en-US/Firefox%20{version}.dmg", json_search_string="LATEST_FIREFOX_VERSION", scraper=scrape_mozilla),
    App(name="Firefox ESR", app_url="https://product-details.mozilla.org/1.0/firefox_versions.json", download_url_template="https://download-installer.cdn.mozilla.net/pub/firefox/releases/{version}/mac/en-US/Firefox%20{version}.dmg", json_search_string="FIREFOX_ESR", scraper=scrape_mozilla),
    App(name="FreeMind", app_url="https://freemind.sourceforge.io/wiki/index.php/Download", download_url_template="http://prdownloads.sourceforge.net/freemind/FreeMind_{version}.dmg", scraper=scrape_freemind),
    App(name="fsmonitor", app_url="https://fsmonitor.com/FSMonitor/Archives/appcast2.xml", sparkle_version_key="shortVersionString", scraper=scrape_sparkle),
    App(name="Gemini", app_url="https://update.googleapis.com/service/update2/json", scraper=scrape_gemini),
    App(name="GIMP", app_url="https://gimp.org/downloads", scraper=scrape_gimp),
    App(name="GitHub Desktop", download_url="https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64", scraper=scrape_githubdesktop),
    App(name="Google Chrome", app_url="https://versionhistory.googleapis.com/v1/chrome/platforms/mac/channels/stable/versions/all/releases?filter=fraction%3E0.01,endtime=none&order_by=version%20desc", download_url="https://dl.google.com/chrome/mac/stable/accept_tos%3Dhttps%253A%252F%252Fwww.google.com%252Fintl%252Fen_ph%252Fchrome%252Fterms%252F%26_and_accept_tos%3Dhttps%253A%252F%252Fpolicies.google.com%252Fterms/googlechrome.pkg", scraper=scrape_googlechrome),
    App(name="Google Earth Pro", app_url="https://support.google.com/earth/answer/168344?sjid=18200233394791621691-AP", scraper=scrape_googleearthpro),
    App(name="GPG Tools", app_url="https://gpgtools.org", scraper=scrape_gpgtools),
    App(name="HandBrake", app_url="https://github.com/handbrake/handbrake", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="HandBrakeCLI", app_url="https://github.com/handbrake/handbrake", file_search_strings=["CLI", ".dmg"], scraper=scrape_github),
    App(name="iMazing Profile Editor", app_url="https://downloads.imazing.com/com.DigiDNA.iMazingProfileEditorMac.xml", scraper=scrape_imazingprofileeditor),
    App(name="Insomnia", app_url="https://github.com/Kong/insomnia", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="IntelliJ IDEA", download_url="https://download.jetbrains.com/product?code=II&latest&distribution=macM1", scraper=scrape_intellijidea),
    App(name="Isadora", app_url="https://support.troikatronix.com/support/solutions/folders/5000277523", download_url="https://troikatronix.com/get-it/", scraper=scrape_isadora),
    App(name="itsycal", app_url="https://s3.amazonaws.com/itsycal/itsycal.xml", scraper=scrape_itsycal),
    App(name="Jamf Compliance Editor", app_url="https://github.com/Jamf-Concepts/jamf-compliance-editor", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="PPPC Utility", app_url="https://github.com/jamf/PPPC-Utility", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Jamf Printer Manager", app_url="https://github.com/jamf/jamf-printer-manager", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Jamf Replicator", app_url="https://github.com/jamf/Replicator", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Jamf Sync", app_url="https://github.com/jamf/JamfSync", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="JamfCheck", app_url="https://github.com/txhaflaire/JamfCheck", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="jamfHelper Constructor", app_url="https://github.com/BIG-RAT/jhc", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Joplin", app_url="https://github.com/laurent22/joplin", file_search_strings=["arm64", ".zip"], scraper=scrape_github),
    App(name="jq", app_url="https://github.com/jqlang/jq", file_search_strings=["macos-arm64"], scraper=scrape_github),
    App(name="Karabena Elements", app_url="https://github.com/pqrs-org/Karabiner-Elements", file_search_strings=["dmg"], scraper=scrape_github),
    App(name="KeepassXC", app_url="https://github.com/keepassxreboot/keepassxc", file_search_strings=["arm64.dmg"], scraper=scrape_github),
    App(name="LabChart", app_url="https://www.adinstruments.com/support/downloads/mac/labchart", scraper=scrape_labchart),
    App(name="logi Options+", app_url="https://support.logi.com/hc/en-au/articles/1500005516462-Logi-Options-Release-Notes", download_url="https://download01.logi.com/web/ftp/pub/techsupport/optionsplus/logioptionsplus_installer.zip", scraper=scrape_logioptionsplus),
    App(name="Logi Tune", app_url="https://support.logi.com/api/v2/help_center/en-us/articles.json?label_names=webcontent=productdownload,webos=mac-macos-x-11.0", scraper=scrape_logitune),
    App(name="LowProfile", app_url="https://github.com/ninxsoft/LowProfile", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="LuLu", app_url="https://github.com/objective-see/LuLu", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="mafft", app_url="https://mafft.cbrc.jp/alignment/software", scraper=scrape_mafft),
    App(name="MakeMKV", app_url="https://www.makemkv.com", scraper=scrape_makemkv),
    App(name="Managed App Schema Builder", app_url="https://github.com/BIG-RAT/Managed-App-Schema-Builder", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Microsoft AutoUpdater", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSau04.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Company Portal", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSau04.xml", download_url="https://go.microsoft.com/fwlink/?linkid=853070", scraper=scrape_microsoft_plist),
    App(name="Microsoft Company Portal - No MAU", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSau04.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Edge", app_url="https://edgeupdates.microsoft.com/api/products/stable", scraper=scrape_microsoft_edge),
    App(name="Microsoft Excel", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409XCEL2019.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Office", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSWD2019.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Office Business Pro", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSWD2019.xml", download_url="https://go.microsoft.com/fwlink/?linkid=2009112", scraper=scrape_microsoft_plist),
    App(name="Microsoft OneDrive", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409ONDR18.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft OneNote", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409ONMC2019.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Outlook", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409OPIM2019.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft PowerPoint", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409PPT32019.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Quick Assist", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSQA01.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Remote Help", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSRH01.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Teams 2", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409TEAMS21.xml", scraper=scrape_microsoft_plist),
    App(name="Windows App", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSRD10.xml", scraper=scrape_microsoft_plist),
    App(name="Microsoft Word", app_url="https://officecdnmac.microsoft.com/pr/C1297A47-86C4-4C1F-97FA-950631F94777/MacAutoupdate/0409MSWD2019.xml", scraper=scrape_microsoft_plist),
    App(name="Mist CLI", app_url="https://github.com/ninxsoft/mist-cli", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Mist", app_url="https://github.com/ninxsoft/Mist", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="MP4Joiner", app_url="https://www.mp4joiner.org/en", download_url_template="https://ixpeering.dl.sourceforge.net/project/mp4joiner/MP4Tools/{version}/MP4Tools-{version}-MacOSX.dmg", scraper=scrape_mp4joiner),
    App(name="MP4Splitter", app_url="https://www.mp4joiner.org/en", download_url_template="https://ixpeering.dl.sourceforge.net/project/mp4joiner/MP4Tools/{version}/MP4Tools-{version}-MacOSX.dmg", scraper=scrape_mp4joiner),
    App(name="MQTT Explorer", app_url="https://github.com/thomasnordquist/MQTT-Explorer", file_search_strings=["mac.zip"], scraper=scrape_github),
    App(name="MUT", app_url="https://github.com/jamf/mut", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="MySQLWorkbench", app_url="https://dev.mysql.com/downloads/workbench/?os=33", useragent="curl/8.7.1", scraper=scrape_mysqlworkbench),
    App(name="Apache NetBeans", app_url="https://github.com/Friends-of-Apache-NetBeans/netbeans-installers", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Nextcloud", app_url="https://github.com/nextcloud-releases/desktop", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Nextpad++", app_url="https://github.com/nextpad-plus-plus/nextpad-plus-plus-macos", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Nitro PDF Pro", app_url="https://downloads.gonitro.com/macos/pro.rss", scraper=scrape_nitropdfpro),
    App(name="Nudge", app_url="https://github.com/macadmins/nudge", file_search_strings=["Nudge_Suite"], scraper=scrape_github),
    App(name="NVivo", app_url="https://techcenter.qsrinternational.com/Content/welcome/toc_welcome.htm", download_url_template="https://download.qsrinternational.com/Software/NVivo{version_maj}forMac/NVivo.dmg", scraper=scrape_nvivo),
    App(name="OBS Studio", app_url="https://github.com/obsproject/obs-studio", file_search_strings=["Apple.dmg"], scraper=scrape_github),
    App(name="Obsidian", app_url="https://github.com/obsidianmd/obsidian-releases", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Okta Verify", app_url="https://integrator-1080591-admin.okta.com/api/v1/artifacts/OKTA_VERIFY_MACOS/latest?releaseChannel=GA", scraper=scrape_oktaverify),
    App(name="OpenVPN Connect", download_url="https://openvpn.net/downloads/openvpn-connect-v3-macos.dmg", scraper=scrape_openvpnconnect),
    App(name="Opera", app_url="https://download.opera.com/download/get/?partner=www&opsys=MacOS", scraper=scrape_opera),
    App(name="Oracle Java 8", app_url="https://javadl-esd-secure.oracle.com/update/mac/map-mac-aarch64-1.8.0.xml", scraper=scrape_oraclejava8),
    App(name="Orion", app_url="https://cdn.kagi.com/updates/26_0/appcast.xml", sparkle_version_key="shortVersionString", sparkle_latest_last=True, scraper=scrape_sparkle),
    App(name="Pacifist", app_url="https://www.charlessoft.com/cgi-bin/pacifist_sparkle.cgi", scraper=scrape_pacifist),
    App(name="Parallels", app_url="https://parallels.com/directdownload/pd", scraper=scrape_parallels),
    App(name="pgAdmin 4", app_url="https://pgadmin-archive.postgresql.org/pgadmin4/index.html", download_url_template="https://pgadmin-archive.postgresql.org/pgadmin4/v{version}/macos/pgadmin4-{version}-arm64.dmg", scraper=scrape_pgadmin4),
    App(name="Plex Media Player", app_url="https://plex.tv/api/downloads/3.json", json_search_string="Mac", scraper=scrape_plex),
    App(name="Plex Media Server", app_url="https://plex.tv/api/downloads/5.json", json_search_string="MacOS", scraper=scrape_plex),
    App(name="Plugdata", app_url="https://github.com/plugdata-team/plugdata", file_search_strings=["Universal.pkg"], scraper=scrape_github),
    App(name="Poll Everywhere", app_url="https://polleverywhere-app.s3.amazonaws.com/mac-stable/appcast.xml", sparkle_version_key="version", scraper=scrape_sparkle),
    App(name="Postman", app_url="https://www.postman.com/mkapi/release.json", download_url="https://dl.pstmn.io/download/latest/osx_arm64", scraper=scrape_postman),
    App(name="Powershell LTS", app_url="https://github.com/Powershell/Powershell", file_search_strings=["lts", "osx-arm64.pkg"], scraper=scrape_github),
    App(name="Powershell", app_url="https://github.com/Powershell/Powershell", file_search_strings=["osx-arm64.pkg"], scraper=scrape_github),
    App(name="Praat", app_url="https://github.com/praat/praat.github.io", file_search_strings=["dmg"], scraper=scrape_github),
    App(name="Proxyman", app_url="https://github.com/ProxymanApp/Proxyman", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Prune", app_url="https://github.com/BIG-RAT/Prune", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Pulsar", app_url="https://github.com/pulsar-edit/pulsar", file_search_strings=["arm64.dmg"], scraper=scrape_github),
    App(name="PyCharm", app_url="https://data.services.jetbrains.com/products?code=PCP&release.type=release&_=1767045118843", scraper=scrape_pycharm),
    App(name="PyMOL LTS", app_url="https://www.pymol.org/", href_match_index=1, scraper=scrape_pymol),
    App(name="PyMOL", app_url="https://www.pymol.org/", href_match_index=0, scraper=scrape_pymol),
    App(name="Python", app_url="https://www.python.org/downloads/", scraper=scrape_python),
    App(name="QLab", app_url="https://qlab.app/appcast/v5/", sparkle_version_key="shortVersionString", scraper=scrape_sparkle),
    App(name="R", app_url="https://cran.rstudio.com/bin/macosx", scraper=scrape_r),
    App(name="Raspberry Pi Imager", download_url="https://downloads.raspberrypi.org/imager/imager_latest.dmg", scraper=scrape_raspberrypiimager),
    App(name="SAP Privileges", app_url="https://github.com/SAP/macOS-enterprise-privileges", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Sassafras KeyAccess Mac", app_url="https://solutions.teamdynamix.com/TDClient/1965/Portal/KB/Article/169236/Current-ITAM-Downloads", scraper=scrape_sassafraskeyaccessmac),
    App(name="Sequel Pro", app_url="https://github.com/sequelpro/sequelpro", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="SF Symbols", app_url="https://developer.apple.com/sf-symbols/", scraper=scrape_sfsymbols),
    App(name="shellcheck", app_url="https://github.com/koalaman/shellcheck", file_search_strings=["darwin.aarch64.tar.xz"], scraper=scrape_github),
    App(name="Signal", app_url="https://updates.signal.org/desktop/latest-mac.yml", download_url_template="https://updates.signal.org/desktop/signal-desktop-mac-universal-{version}.dmg", scraper=scrape_signal),
    App(name="Slack", app_url="https://slack.com/ssb/download-osx-universal", scraper=scrape_slack),
    App(name="Snagit", app_url="https://support.techsmith.com/hc/en-us/articles/37938520706957-Snagit-Mac-2025-Version-History", download_url_template="https://download.techsmith.com/snagitmac/releases/{version}/snagit.dmg", scraper=scrape_snagit),
    App(name="SQLite Browser", app_url="https://github.com/sqlitebrowser/sqlitebrowser", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Story Architect", app_url="https://github.com/sequelpro/sequelpro", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Storyboarder", app_url="https://github.com/wonderunit/storyboarder", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Subler", app_url="https://github.com/SublerApp/Subler", file_search_strings=[".zip"], scraper=scrape_github),
    App(name="Sublime Merge", app_url="https://www.sublimemerge.com/updates/stable_update_check", download_url_template="https://download.sublimetext.com/sublime_merge_build_{version}_mac.zip", scraper=scrape_sublime),
    App(name="Sublime Text", app_url="https://www.sublimetext.com/updates/4/stable_update_check", download_url_template="https://download.sublimetext.com/sublime_text_build_{version}_mac.zip", scraper=scrape_sublime),
    App(name="SupportApp", app_url="https://github.com/root3nl/SupportApp", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Suspicous Package", app_url="https://www.mothersruin.com/software", scraper=scrape_suspiciouspackage),
    App(name="SwiftDialog", app_url="https://github.com/swiftDialog/swiftDialog", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="TeamViewer", app_url="https://download.teamviewer.com/download/update/macupdates.xml?version=15.1.1&os=macos&osversion=26.5.1", sparkle_version_key="version", scraper=scrape_sparkle),
    App(name="TeamViewerQS", app_url="https://www.teamviewer.com/en-au/solutions/use-cases/quicksupport/", scraper=scrape_teamviewerqs),
    App(name="Telegram", app_url="https://macos.telegram.org", download_url="https://osx.telegram.org/updates/Telegram.dmg", scraper=scrape_telegram),
    App(name="The Unarchiver", app_url="https://theunarchiver.com", scraper=scrape_theunarchiver),
    App(name="Thunderbird", app_url="https://product-details.mozilla.org/1.0/thunderbird_versions.json", download_url_template="https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/{version}/mac/en-US/Thunderbird%20{version}.dmg", json_search_string="LATEST_THUNDERBIRD_VERSION", scraper=scrape_mozilla),
    App(name="Thunderbird ESR", app_url="https://product-details.mozilla.org/1.0/thunderbird_versions.json", download_url_template="https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/{version}/mac/en-US/Thunderbird%20{version}.dmg", json_search_string="THUNDERBIRD_ESR", scraper=scrape_mozilla),
    App(name="Touch Designer", app_url="https://derivative.ca/download", download_url_template="https://download.derivative.ca/TouchDesigner.{version}.arm64.dmg", scraper=scrape_touchdesigner),
    App(name="Transmission", app_url="https://github.com/transmission/transmission", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="UTM", app_url="https://github.com/utmapp/UTM", file_search_strings=[".dmg"], scraper=scrape_github),
    App(name="Visual Studio Code", app_url="https://update.code.visualstudio.com/api/update/darwin-universal/stable/dc96b837cf6bb4af9cd736aa3af08cf8279f7685", scraper=scrape_visualstudiocode),
    App(name="VLC", app_url="https://www.videolan.org/vlc/download-macosx.html", scraper=scrape_vlc),
    App(name="Voodoo Pad", app_url="https://www.voodoopad.com/", download_url_template="https://voodoopad.s3.amazonaws.com/VoodooPad-{version}.zip", scraper=scrape_voodoopad),
    App(name="Webex", app_url="https://help.webex.com/en-us/article/mqkve8/Webex-App-%7C-Release-notes", useragent="curl/8.7.1", download_url="https://www.webex.com/downloads.html", scraper=scrape_webex),
    App(name="WhatsApp", download_url="https://web.whatsapp.com/desktop/mac_native/release/?configuration=Release", scraper=scrape_whatsapp),
    App(name="Wireshark", app_url="https://www.wireshark.org/update/0/Wireshark/3.6.3/macOS/x86-64/en-US/stable.xml", scraper=scrape_wireshark),
    App(name="XQuartz", app_url="https://github.com/xquartz/xquartz", file_search_strings=[".pkg"], scraper=scrape_github),
    App(name="Yubico Authenticator", download_url="https://developers.yubico.com/yubioath-flutter/Releases/yubico-authenticator-latest-mac.dmg", scraper=scrape_yubicoauth),
    App(name="Zoom", app_url="https://zoom.us/rest/download?os=mac", download_url="https://zoom.us/client/latest/ZoomInstallerIT.pkg", scraper=scrape_zoom),
    App(name="Zotero", app_url="https://www.zotero.org/download/", scraper=scrape_zotero),
    App(name="MestReNova", app_url="https://mestrelab.com", scraper=scrape_mestrenova)
]
